name: dart_firebase_notification
description: notification
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:

  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  dart_firebase_admin:
    path: ../dart_firebase_admin
  firebase_dart: ^1.4.3
  firedart: ^0.9.8
  googleapis_auth: ^1.6.0
  http: ^1.3.0
