name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cache:
    path: ../cache

  crypto: ^3.0.3
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.15.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.3.0
  meta: ^1.9.1

  sign_in_with_apple: ^6.1.1
  uuid: ^4.2.1
  very_good_analysis: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
flutter:
  generate: true
