name: form_inputs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  formz: ^0.8.0


dev_dependencies:
  very_good_analysis: ^7.0.0
