name: core
description: Package core pour Wibbo - modèles, services et utilitaires partagés
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  cloud_firestore: ^5.6.0
  cloud_firestore_odm: ^1.0.0-dev.88
  firebase_auth: ^5.7.0
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  build_runner: ^2.4.15
  cloud_firestore_odm_generator: ^1.0.0-dev.89
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
